name: Run Golang App

on:
  push:
    branches: [ push ]
  schedule:
    - cron:  '0 1-11/2 * * *' # UTC 기준 0시부터 12시까지 매시 정각

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    environment: 
      name: release

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22' # Go 버전을 프로젝트에 맞게 조정하세요

    - name: Create .env file
      run: |
        echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}" >> .env
        echo "SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }}" >> .env
        echo "SPREADSHEET_NAME=${{ secrets.SPREADSHEET_NAME }}" >> .env

    - name: Build
      run: go build -o wishket cmd/wishket/main.go

    - name: Run
      run: ./wishket
